### ISSUE TITLE
Add ability to omit/exclude directories

### ISSUE THREAD

**Issue by darksidemilk** [EliteLoser/GetSTFolderSize#3]
I attempted to add some /XD and /XF to the robocopy command that is run with the roboOnly parameter enabled but kept getting errors saying that /XD foldername was an invalid parameter for robocopy.
Not sure why, I kept trying to take out one param at a time but no good.

If it's possible to add the ability to exclude specific/regex folders and files that would be handy.

i.e. if I want to compare a source to a destination to create a backup progress for backing up a user folder where I would be excluding common cloud drive folders (googldrive, onedrive, dropbox etc.) as well as various system files and some filetypes. If I could exclude those I could run my backup as a job and do a write-progress loop to show the progress based on the source and destination sizes. This could be done for any copy job really. Since your function gets the size so fast, it wouldn't quite be real time progress but it could be fairly close.

**Comment by EliteLoser** [comment]
I think this should be OK:

```PowerShell
Get-STFolderSize . -RoboOnly -ExcludeDirectory GetSTFolderSize -ExcludeFile *.txt
```
```
Path             : C:\temp
TotalBytes       : 529656134
TotalMBytes      : 505.1195
TotalGBytes      : 0.4933
DirCount         : 69
FileCount        : 122
DirFailed        : 0
FileFailed       : 0
TimeElapsed      : 0.0937
StartedTime      : 12/7/2018 9:38:16 PM
EndedTime        : 12/7/2018 9:38:16 PM
CopiedDirCount   : 67
CopiedFileCount  : 121
CopiedBytes      : 529656098
SkippedDirCount  : 2
SkippedFileCount : 1
SkippedBytes     : 36
```

The new properties (the last 6) will magically appear when you use either the -ExcludeDirectory or -ExcludeFile parameter or both. I will create a branch and put the code I have there. As far as I can tell, it's ready to rock'n roll?

Arrays of strings with names/paths/wildcards for files and names/paths for directories, according to the robocopy help text, are accepted for the parameter, the way robocopy itself eats them afterwards.

**Comment by darksidemilk** [comment]
That was so fast! I’ll try it out as soon as I can.

JJ Fullmer
Arrowhead Dental Lab
IT Operations Engineer
801-572-7253
jfullmer@arrowheaddental.com

**Comment by EliteLoser** [comment]
It's in this commit, along with some added standards conformance :) https://github.com/EliteLoser/GetSTFolderSize/commit/eba0f4b0c58f5e2b97c4d70a108b386dd922d66d

**Comment by EliteLoser** [comment]
I merged it in, published to the gallery, downloaded from there, tested, and also created some basic Pester 4.x+ tests for the function. Works for me, let me know if you have issues. Closing this issue.
